#remote
server:
  port: 8088

spring:
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  redis:
    database: 0  # Redis数据库索引（默认为0）
    host: localhost # Redis服务器地址
    port: 6379   # Redis服务器连接端口
    password: "961209miao"  # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0  # 连接池中的最小空闲连接
    timeout: 300  # 连接超时时间（毫秒）
  cache:
    redis:
      timeToLive: 1000000 #毫秒
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/small2?setUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: "961209miao"


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


